"""Markdown report generation for SpecGap."""

from __future__ import annotations

from .models import SOURCE_LABELS, SpecInput
from .semantic_diff import DiffResult
from .triangulation import TriangulationSummary, triangulate_analysis
from .z3_checker import ATOM_HUMAN, ConsistencyResult, ImplicationResult

DISCLAIMER = (
    "SpecGap does not prove the spec is correct. It identifies likely semantic "
    "divergence zones and checks extracted constraints (via Z3 over the abstract "
    "sandbox model) for consistency or implication failure."
)

EMPTY_INTENT_WARNING = (
    "Stakeholder intent yielded zero extracted constraints. Divergence cannot "
    "be checked against an empty intent. This is NOT a clean result — it is an "
    "extraction failure."
)

PASSING_MEANING = (
    "Passing means no semantic divergence was detected within the abstract "
    "sandbox model and extracted constraints. It does not prove semantic "
    "correctness."
)

HUMAN_ANNOTATION_HEADER = "## Human Annotation (outside tool evaluation)"


def _human_annotation_block(text: str) -> list[str]:
    """Render author-supplied example context, visually outside tool output."""
    lines = [
        HUMAN_ANNOTATION_HEADER,
        "",
        "> **HUMAN NOTE**",
        "> This annotation is explanatory context supplied by the example author.",
        "> It is not generated by SpecGap.",
        ">",
    ]
    for paragraph in text.strip().split("\n"):
        paragraph = paragraph.strip()
        if paragraph:
            lines.append(f"> {paragraph}")
    lines.append("")
    return lines


def _constraint_lines(by_source: dict) -> list[str]:
    lines: list[str] = []
    for source in ("stakeholder_intent", "formalized_policy", "implementation_claim"):
        lines.append(f"**{SOURCE_LABELS[source]}**")
        constraints = by_source[source]
        if not constraints:
            lines.append("- _(no constraints extracted)_")
        for c in constraints:
            flag = " _(ambiguous)_" if c.ambiguous else ""
            extra = ""
            if c.method == "fuzzy":
                extra = (f" _(source=fuzzy, confidence={c.confidence:.2f}, "
                         f"requires_human_review="
                         f"{str(c.requires_human_review).lower()})_")
            lines.append(f"- `{c.name}` — {c.label()} "
                         f"[{c.category}/{c.strength}, via {c.method}]{flag}{extra}")
        lines.append("")
    return lines


def _counterexample_lines(result: ImplicationResult) -> list[str]:
    lines: list[str] = []
    for atom in result.counterexample_atoms:
        human = ATOM_HUMAN.get(atom, atom)
        lines.append(f"- `{atom} = true` — {human}")
    if not lines:
        lines.append("- _(empty behavior — all atoms false)_")
    return lines


def _implication_block(result: ImplicationResult) -> list[str]:
    lines = [f"### {result.antecedent_label} ⇒ {result.consequent_label}", ""]
    if result.status == "no_consequent":
        lines.append("- No strict target constraints to check against. _(skipped)_")
        return lines + [""]
    if result.implied:
        lines.append(f"- **Result: implication holds.** Z3 returned `unsat` for the "
                     f"negation — every behavior permitted by {result.antecedent_label} "
                     f"is also permitted by {result.consequent_label}.")
        return lines + [""]
    lines.append(f"- **Result: implication FAILS.** Z3 returned `sat` for the negation: "
                 f"there is a behavior permitted by {result.antecedent_label} that "
                 f"{result.consequent_label} forbids.")
    lines.append(f"- Violated target constraint(s): "
                 f"{', '.join(f'`{v}`' for v in result.consequent_violated)}")
    lines.append("")
    lines.append("Counterexample behavior:")
    lines.extend(_counterexample_lines(result))
    lines.append("")
    lines.append(f"Therefore **{result.antecedent_label}** permits a behavior that "
                 f"**{result.consequent_label}** appears to forbid.")
    return lines + [""]


def _candidate_constraint_lines(constraints: list) -> list[str]:
    """Render an extracted-constraint bullet list (shared style with the
    standard report's constraint section)."""
    if not constraints:
        return ["- _(no constraints extracted)_"]
    lines: list[str] = []
    for c in constraints:
        flag = " _(ambiguous)_" if c.ambiguous else ""
        extra = ""
        if c.method == "fuzzy":
            extra = (f" _(source=fuzzy, confidence={c.confidence:.2f}, "
                     f"requires_human_review="
                     f"{str(c.requires_human_review).lower()})_")
        lines.append(f"- `{c.name}` — {c.label()} "
                     f"[{c.category}/{c.strength}, via {c.method}]{flag}{extra}")
    return lines


def _triangulation_lines(summary: TriangulationSummary) -> list[str]:
    lines = [
        "Structural divergence analysis and Z3 implication checking **operate "
        "independently** over extracted constraints. **Disagreement is preserved** "
        "because the two mechanisms capture different abstraction-level properties "
        "(name-level weakening lattice vs propositional sandbox model). Do not "
        "treat agreement as a merged verdict — see `docs/TCB.md`, "
        "`docs/ENCODING.md`.",
        "",
        "| Layer | Structural | Z3 implication | Agreement | Counterexample |",
        "| --- | --- | --- | --- | --- |",
    ]
    for r in summary.records:
        agree = "yes" if r.agreement else "**no**"
        ce = "yes" if r.counterexample_present else "no"
        lines.append(
            f"| {r.layer} | {r.structural_diff} | {r.z3_implication} | {agree} | {ce} |"
        )
    lines.append("")
    if summary.intent_empty:
        lines.append(
            "_Intent extraction yielded zero constraints — Z3 checks were skipped "
            "and triangulation agreement is **no** (indeterminate, not corroborated)._"
        )
    elif summary.any_disagreement:
        lines.append(
            "_At least one layer shows **disagreement** between structural diff and "
            "Z3. Treat both signals as heterogeneous evidence from independent "
            "mechanisms; do not collapse to a single verdict._"
        )
    else:
        lines.append(
            "_Structural diff and Z3 implication outcomes **agree** for all layers "
            "checked — within the TCB scope below, not as end-to-end assurance._"
        )
    lines.append("")
    lines.append("**TCB scope for this triangulation:**")
    for item in summary.records[0].tcb_scope if summary.records else []:
        lines.append(f"- {item}")
    lines.append("")
    return lines


def build_candidate_report(evaluation, extractor_mode: str = "rule") -> str:
    """Render the candidate evaluation mode report.

    ``evaluation`` is a ``candidate_eval.CandidateEvaluation``.
    """
    spec = evaluation.spec
    results = evaluation.results                       # mechanically ordered
    by_id = sorted(results, key=lambda r: r.candidate.id)
    intent_empty = not evaluation.intent_constraints
    passed = [r for r in results if r.passed]
    out: list[str] = []

    out.append(f"# SpecGap Candidate Evaluation Report — {spec.title}")
    out.append("")
    out.append(f"> {DISCLAIMER}")
    out.append("")
    out.append("_Candidate evaluation mode: spec-conditioned candidate evaluation. "
               "One extracted stakeholder intent is used to evaluate multiple "
               "candidate policy implementations. SpecGap discriminates between "
               "candidate implementations by checking whether extracted policy "
               "constraints preserve stakeholder intent within the abstract model. "
               "This is a vericoding-adjacent workflow, not synthesis or verified "
               "code generation._")
    out.append("")

    # Summary
    out.append("## Summary")
    out.append("")
    if intent_empty:
        out.append(f"- ⚠️ **EXTRACTION FAILURE — NOT A CLEAN RESULT.** "
                   f"{EMPTY_INTENT_WARNING} With no intent constraints, every "
                   f"candidate trivially 'passes' and the candidate ordering "
                   f"below is not meaningful. If the intent uses paraphrased "
                   f"language, re-run "
                   f"with `--extractor fuzzy`.")
    out.append(f"- Candidates evaluated: {len(results)}.")
    out.append(f"- Passing candidates: {len(passed)} of {len(results)}.")
    out.append(f"- Extraction mode: `{extractor_mode}`.")
    out.append("")

    # Stakeholder intent
    out.append("## Stakeholder Intent")
    out.append("")
    out.append(spec.stakeholder_intent)
    out.append("")
    out.append("Extracted intent constraints — the specification every candidate "
               "is evaluated against:")
    out.append("")
    out.extend(_candidate_constraint_lines(evaluation.intent_constraints))
    if spec.expected:
        out.append("")
        out.extend(_human_annotation_block(spec.expected))
    out.append("")

    # Candidate summaries
    out.append("## Candidate Summaries")
    out.append("")
    for r in by_id:
        out.append(f"### Candidate {r.candidate.id} — {r.candidate.label}")
        out.append("")
        out.append(f"> {r.candidate.policy}")
        out.append("")
        out.append("Extracted constraints:")
        out.append("")
        out.extend(_candidate_constraint_lines(r.constraints))
        out.append("")

    # Validation outcomes
    out.append("## Validation Outcomes")
    out.append("")
    out.append("Each candidate's extracted constraints are checked for implication "
               "of the stakeholder intent. A `sat` result for the negated query is "
               "a concrete implication failure with a counterexample behavior.")
    out.append("")
    out.append("| Candidate | Result | Implication failures | "
               "Violated intent constraint(s) |")
    out.append("| --- | --- | --- | --- |")
    for r in by_id:
        verdict = "PASS" if r.passed else "FAIL"
        violated = ("—" if r.passed
                    else ", ".join(f"`{v}`" for v in r.implication.consequent_violated))
        out.append(f"| Candidate {r.candidate.id} | {verdict} | "
                   f"{r.failure_count} | {violated} |")
    out.append("")

    # Counterexamples
    out.append("## Counterexamples")
    out.append("")
    failing = [r for r in by_id if not r.passed]
    if failing:
        for r in failing:
            violated = ", ".join(f"`{v}`"
                                 for v in r.implication.consequent_violated)
            out.append(f"**Candidate {r.candidate.id}** permits a behavior the "
                       f"stakeholder intent forbids (violates {violated}):")
            out.append("")
            out.extend(_counterexample_lines(r.implication))
            out.append("")
    else:
        out.append("_No counterexamples: no implication failure against extracted "
                   "intent constraints for any candidate._")
        out.append("")

    # Candidate ordering
    out.append("## Candidate Ordering")
    out.append("")
    out.append("Candidates are mechanically ordered by detected implication "
               "failures over extracted constraints: passing candidates first, "
               "then ascending implication-failure count. Ties keep input order. "
               "This ordering is not a leaderboard and not a quality score — it "
               "reports only how many intent constraints each candidate fails to "
               "preserve within the abstract model.")
    out.append("")
    for r in results:
        if r.passed:
            note = ("PASS — no implication failure against extracted intent "
                    "constraints")
        else:
            note = (f"FAIL — {r.failure_count} implication failure(s); violates "
                    f"{', '.join(r.implication.consequent_violated)}")
        out.append(f"{r.rank}. **Candidate {r.candidate.id}** "
                   f"({r.candidate.label}) — {note}")
    out.append("")

    # Limitations
    out.append("## Limitations")
    out.append("")
    out.append(f"- **{PASSING_MEANING}**")
    out.append(f"- {DISCLAIMER}")
    out.append("- This is spec-conditioned candidate *evaluation* — a "
               "vericoding-adjacent workflow, not verified synthesis. SpecGap does "
               "not generate or repair the candidate policies; it only "
               "discriminates between candidates supplied to it.")
    out.append("- Candidate constraints are extracted with the same "
               "fixed-vocabulary rule extractor; unrecognized phrasing is silently "
               "not extracted, so a candidate could pass by omission rather than "
               "by correctness.")
    out.append("- The Z3 model is a small propositional abstraction of sandbox "
               "behavior, not a model of a real kernel or runtime.")
    out.append("- Counterexamples are illustrative behaviors, not exploit proofs.")
    out.append("- The candidate ordering reflects only implication "
               "success/failure against the extracted intent; it is not a "
               "quality, performance, or security "
               "score.")
    out.append("")

    return "\n".join(out)


def build_report(spec: SpecInput, by_source: dict, diff_result: DiffResult,
                 implications: list[ImplicationResult],
                 consistencies: list[ConsistencyResult],
                 extractor_mode: str = "rule") -> str:
    """Render the full Markdown divergence report."""
    failed = [r for r in implications if r.status == "implication_failed"]
    high = diff_result.high_severity
    intent_empty = not by_source["stakeholder_intent"]
    triangulation = triangulate_analysis(diff_result, implications,
                                        intent_empty=intent_empty)
    out: list[str] = []

    out.append(f"# SpecGap Divergence Report — {spec.title}")
    out.append("")
    out.append(f"> {DISCLAIMER}")
    out.append("")

    # Summary
    out.append("## Summary")
    out.append("")
    if intent_empty:
        out.append(f"- ⚠️ **EXTRACTION FAILURE — NOT A CLEAN RESULT.** "
                   f"{EMPTY_INTENT_WARNING}")
        out.append(f"- Extraction mode: `{extractor_mode}`. If the intent uses "
                   f"paraphrased language, re-run with `--extractor fuzzy`.")
    else:
        verdict = ("**Semantic divergence detected.**" if (failed or high)
                   else "**No divergence detected** by the current rule set.")
        out.append(f"- {verdict}")
    out.append(f"- Semantic divergences found: {len(diff_result.divergences)} "
               f"({len(high)} high structural severity).")
    out.append(f"- Formal implication checks failed: {len(failed)} of {len(implications)}.")
    inconsistent = [c for c in consistencies if not c.consistent]
    out.append(f"- Internally inconsistent layers: {len(inconsistent)}.")
    if triangulation.any_disagreement:
        out.append("- Triangulation: **disagreement** between structural diff and Z3 "
                   "on at least one layer (see Triangulation Summary).")
    elif not intent_empty:
        out.append("- Triangulation: structural diff and Z3 **agree** on all layers "
                   "(within TCB scope).")
    out.append("")

    # Triangulation Summary
    out.append("## Triangulation Summary")
    out.append("")
    out.extend(_triangulation_lines(triangulation))

    # Inputs
    out.append("## Inputs")
    out.append("")
    for source in ("stakeholder_intent", "formalized_policy", "implementation_claim"):
        out.append(f"- **{SOURCE_LABELS[source]}:** {spec.text_for(source)}")
    if spec.expected_issue:
        out.append("")
        out.extend(_human_annotation_block(spec.expected_issue))
    out.append("")

    # Extracted constraints
    out.append("## Extracted Constraints")
    out.append("")
    if extractor_mode == "fuzzy":
        out.append("_Extraction mode: `fuzzy` — deterministic rule-based parsing "
                   "first, then fuzzy fallback for paraphrases the rules missed. "
                   "Fuzzy-extracted constraints are marked below and require human "
                   "review before they are trusted._")
    else:
        out.append("_Extraction mode: `rule` — deterministic rule-based parsing "
                   "only. Fuzzy/paraphrase-aware extraction is available via "
                   "`--extractor fuzzy`._")
    out.append("")
    out.extend(_constraint_lines(by_source))

    # Divergence table
    out.append("## Semantic Divergence")
    out.append("")
    out.append("| Category | Stakeholder Intent | Formalized Policy | Implementation Claim |")
    out.append("| --- | --- | --- | --- |")
    for row in diff_result.table:
        out.append(f"| {row['category']} | {row['stakeholder_intent']} | "
                   f"{row['formalized_policy']} | {row['implementation_claim']} |")
    out.append("")
    if diff_result.divergences:
        out.append("Detected divergences:")
        out.append("")
        for d in diff_result.divergences:
            out.append(f"- **[{d.kind}]** _(structural severity: {d.severity})_ — "
                       f"{d.summary}")
            out.append(f"  - {d.detail}")
    else:
        out.append("_No structural divergences detected._")
    out.append("")

    # Z3 result
    out.append("## Z3 Formal Check")
    out.append("")
    out.append("Each check asks Z3 whether one layer's constraints **imply** another's. "
               "A `sat` result for the negated query means a permitted-but-forbidden "
               "behavior exists — a concrete implication failure in the abstract "
               "sandbox model.")
    out.append("")
    for result in implications:
        out.extend(_implication_block(result))
    out.append("Internal consistency (each layer satisfiable on its own):")
    out.append("")
    for c in consistencies:
        state = "consistent" if c.consistent else "**INCONSISTENT**"
        out.append(f"- {c.label}: {state} (`z3: {c.z3_check}`)")
    out.append("")

    # Counterexample
    out.append("## Counterexample")
    out.append("")
    if failed:
        for result in failed:
            out.append(f"For **{result.antecedent_label} ⇒ {result.consequent_label}**:")
            out.extend(_counterexample_lines(result))
            out.append("")
    else:
        out.append("_No counterexample: all implication checks held._")
        out.append("")

    # Explanation
    out.append("## Human-Readable Explanation")
    out.append("")
    if intent_empty:
        out.append("SpecGap could not extract any constraints from the stakeholder "
                   "intent, so there was nothing to check the other layers against. "
                   "This is an extraction failure, not a clean result: the absence of "
                   "reported divergence here means the comparison never ran. The "
                   "intent phrasing is outside the rule vocabulary — re-run with "
                   "`--extractor fuzzy` to attempt paraphrase-aware extraction.")
    elif failed:
        primary = failed[0]
        out.append(f"SpecGap extracted the constraints stated in each layer and asked "
                   f"Z3 whether the downstream layers still satisfy the stakeholder "
                   f"intent. They do not. {primary.antecedent_label} permits a "
                   f"behavior — shown in the counterexample above — that the "
                   f"stakeholder intent forbids.")
        out.append("")
        out.append("In plain terms: the wording drifted between what was *asked for*, "
                   "what was *formalized*, and what was *claimed to be implemented*. "
                   "A reviewer reading only one layer would not see the gap. The "
                   "proof obligation was quietly redefined.")
    else:
        out.append("SpecGap found no implication failure between the layers for the "
                   "extracted constraints. This is not a proof of correctness — only "
                   "that no divergence was detected by the current rules.")
    out.append("")

    # Limitations
    out.append("## Limitations")
    out.append("")
    out.append(f"- {DISCLAIMER}")
    out.append("- Constraint extraction is rule-based and recognizes a fixed "
               "vocabulary of sandbox constraints. Unrecognized phrasing is silently "
               "not extracted.")
    out.append("- Fuzzy / paraphrase-aware extraction (`--extractor fuzzy`) is "
               "opt-in and rule-first; fuzzy-extracted constraints are flagged "
               "`requires_human_review` and are not authoritative. The default "
               "`rule` mode is fully deterministic and offline.")
    out.append("- The Z3 model is a small propositional abstraction of sandbox "
               "behavior, not a model of a real kernel or runtime.")
    out.append("- Counterexamples are illustrative behaviors, not exploit proofs.")
    out.append("- A clean report means *no divergence was detected*, not that the "
               "specification is correct.")
    out.append("")

    return "\n".join(out)
